config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/flights", to: "flights#index"
  resources :bookings, only: [:new, :create, :show]
  root "flights#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: "Flight", foreign_key: "departure_airport_id"
  has_many :arriving_flights, class_name: "Flight", foreign_key: "arrival_airport_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"
  has_many :bookings
  has_many :passengers, through: :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(params[:flight_id])
    @booking = @flight.bookings.build
    params[:num_passengers].to_i.times { @booking.passengers.build }
  end

  def create
    # create the new booking and the associated passengers
    @booking = Booking.new(booking_params)
    if @booking.save
      @booking.passengers.each do |passenger|
        PassengerMailer.with(passenger: passenger, booking: @booking).passenger_booked_email.deliver_now
      end
      redirect_to @booking
    else
      render 'new', notice: 'Booking failed', status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end
  
  private
  
  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: %i[name email])
  end
  
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    # TODO: pass search params into the view so they can be prepopulated in the search form rather than query in a view
    if [params[:from_airport_id], params[:to_airport_id], params[:date]].any? 
      # build a query where all three params are optional
      query = Flight.where(nil)
      query = query.where(departure_airport_id: params[:from_airport_id]) if params[:from_airport_id].present?
      query = query.where(arrival_airport_id: params[:to_airport_id]) if params[:to_airport_id].present?
      query = query.where("DATE(departure_time) = ?", params[:date]) if params[:date].present?
      @flights = query.includes(:departure_airport, :arrival_airport)
      @search = {from_airport_id: params[:from_airport_id], to_airport_id: params[:to_airport_id], date: params[:date], num_passengers: params[:num_passengers]}
   else
    @flights = Flight.all.includes(:departure_airport, :arrival_airport)
   end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="isolate -space-y-px rounded-md shadow-sm w-96">
  <%= form_for @booking, local: true do |f| %>
    <%= f.fields_for :passengers do |passenger| %>
      <div class="relative rounded-md rounded-b-none border border-gray-300 px-3 py-2 focus-within:z-10 focus-within:border-indigo-600 focus-within:ring-1 focus-within:ring-indigo-600">
        <%= passenger.label :name, { class: "block text-xs font-medium text-gray-900" } %>
        <%= passenger.text_field :name, { class: "block w-full border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm", placeholder: "Passenger Name" } %>
      </div>
      <div class="relative rounded-md mb-4 rounded-t-none border border-gray-300 px-3 py-2 focus-within:z-10 focus-within:border-indigo-600 focus-within:ring-1 focus-within:ring-indigo-600">
        <%= passenger.label :email, { class: "block text-xs font-medium text-gray-900" } %>
        <%= passenger.email_field :email, { class: "block w-full border-0 p-0 text-gray-900 placeholder-gray-500 focus:ring-0 sm:text-sm", placeholder: "Passenger Email" } %>
      </div>
    <% end %>
    <%= f.hidden_field :flight_id, value: @flight.id %>
    <%= f.submit class: "inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto" %>
  <% end %>
</div>

app/views/bookings/new.html.erb
<h1 class="text-xl font-bold text-indigo-900 mb-4">Book Your Flight</h1>
<div class="divide-y divide-gray-200 overflow-hidden rounded-lg bg-white shadow mb-4">
  <div class="px-4 py-4 sm:px-6">
    <h2 class="text-lg font-semibold text-gray-800">Flight Info</h2>
  </div>
  <div class="px-4 py-4 sm:p-6">
    <dl class="mt-2 grid grid-cols-1 gap-5 md:grid-cols-4">
      <div class="overflow-hidden rounded-lg bg-white px-4 py-5 shadow sm:p-6">
        <dt class="truncate text-xs font-medium text-gray-500">Departing From</dt>
        <dd class="mt-1 text-lg font-semibold tracking-tight text-gray-900"><%= "#{@flight.departure_airport.city} (#{@flight.departure_airport.code})" %></dd>
      </div>
      <div class="overflow-hidden rounded-lg bg-white px-4 py-5 shadow sm:p-6">
        <dt class="truncate text-xs font-medium text-gray-500">Arriving To</dt>
        <dd class="mt-1 text-lg font-semibold tracking-tight text-gray-900"><%= "#{@flight.arrival_airport.city} (#{@flight.arrival_airport.code})" %></dd>
      </div>
      <div class="overflow-hidden rounded-lg bg-white px-4 py-5 shadow sm:p-6">
        <dt class="truncate text-xs font-medium text-gray-500">Departure Date/Time</dt>
        <dd class="mt-1 text-lg font-semibold tracking-tight text-gray-900"><%= @flight.departure_time.strftime("%m/%d/%Y - %l:%M%p") %></dd>
      </div>
      <div class="overflow-hidden rounded-lg bg-white px-4 py-5 shadow sm:p-6">
        <dt class="truncate text-xs font-medium text-gray-500">Flight Duration</dt>
        <dd class="mt-1 text-lg font-semibold tracking-tight text-gray-900"><%= "#{@flight.duration/60} hours" %></dd>
      </div>
    </dl>
  </div>
</div>
<%= render 'form' %>

app/views/bookings/show.html.erb
<h1 class="text-xl font-bold text-indigo-900 mb-4">Congrats on Booking Your Flight!</h1>
<div class="divide-y divide-gray-200 overflow-hidden rounded-lg bg-white shadow mb-4">
  <div class="px-4 py-4 sm:px-6">
    <h2 class="text-lg font-semibold text-gray-800">Your Flight</h2>
  </div>
  <div class="px-4 py-4 sm:p-6">
    <dl class="mt-2 grid grid-cols-1 gap-5 md:grid-cols-4">
      <div class="overflow-hidden rounded-lg bg-white px-4 py-5 shadow sm:p-6">
        <dt class="truncate text-xs font-medium text-gray-500">Departing From</dt>
        <dd class="mt-1 text-lg font-semibold tracking-tight text-gray-900"><%= "#{@booking.flight.departure_airport.city} (#{@booking.flight.departure_airport.code})" %></dd>
      </div>
      <div class="overflow-hidden rounded-lg bg-white px-4 py-5 shadow sm:p-6">
        <dt class="truncate text-xs font-medium text-gray-500">Arriving To</dt>
        <dd class="mt-1 text-lg font-semibold tracking-tight text-gray-900"><%= "#{@booking.flight.arrival_airport.city} (#{@booking.flight.arrival_airport.code})" %></dd>
      </div>
      <div class="overflow-hidden rounded-lg bg-white px-4 py-5 shadow sm:p-6">
        <dt class="truncate text-xs font-medium text-gray-500">Departure Date/Time</dt>
        <dd class="mt-1 text-lg font-semibold tracking-tight text-gray-900"><%= @booking.flight.departure_time.strftime("%m/%d/%Y - %l:%M%p") %></dd>
      </div>
      <div class="overflow-hidden rounded-lg bg-white px-4 py-5 shadow sm:p-6">
        <dt class="truncate text-xs font-medium text-gray-500">Flight Duration</dt>
        <dd class="mt-1 text-lg font-semibold tracking-tight text-gray-900"><%= "#{@booking.flight.duration/60} hours" %></dd>
      </div>
    </dl>
  </div>
</div>
<div class="px-6">
  <div class="mt-6 w-64">
    <div>
      <h2 class="my-2 text-lg font-semibold text-gray-800">Passengers</h2>
    </div>
    <ul role="list" class="-my-5 divide-y divide-gray-200">
      <% @booking.passengers.each do |passenger| %>
        <li class="py-5">
          <div class="relative focus-within:ring-2 focus-within:ring-indigo-500">
            <h3 class="text-sm font-semibold text-gray-800">
              <span class="absolute inset-0" aria-hidden="true"></span>
              <%= passenger.name %>
            </a>
          </h3>
          <p class="mt-1 text-sm text-gray-600 line-clamp-2"><%= passenger.email %></p>
        </div>
      </li>
    <% end %>
  </ul>
  <%= link_to "Back to Flights", root_path, class: "my-4 inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto" %>
</div>

app/views/flights/_flight.html.erb
<tr>
  <td class="relative py-4 pl-4 sm:pl-6 pr-3 text-sm">
    <div class="font-medium text-gray-900"><%= "#{flight.departure_airport.code} -> #{flight.arrival_airport.code}" %></div>
    <div class="mt-1 flex flex-col text-gray-500 sm:block lg:hidden">
      
      <span><%= "#{flight.duration/60} hrs" %></span>
    </div>
  </td>
  <td class="hidden px-3 py-3.5 text-sm text-gray-500 lg:table-cell"><%= flight.departure_airport.city %></td>
  <td class="hidden px-3 py-3.5 text-sm text-gray-500 lg:table-cell"><%= flight.arrival_airport.city %></td>
  <td class="hidden px-3 py-3.5 text-sm text-gray-500 lg:table-cell"><%= "#{flight.duration/60} hours" %></td>
  <td class="px-3 py-3.5 text-sm text-gray-500">
    <div class="sm:hidden"><%= flight.departure_time.strftime("%m/%d/%Y-%l:%M%P") %></div>
    <div class="hidden sm:block"><%= flight.departure_time.strftime("%m/%d/%Y - %l:%M%p") %></div>
  </td>
  <td class="relative py-3.5 pl-3 pr-4 sm:pr-6 text-right text-sm font-medium">
    <% if @search.try!(:[], :num_passengers) != nil and (@search[:num_passengers].to_i > 0)  %>
    <%= button_to "Book It!", new_booking_path, method: :get, data: {turbo: false}, params: { flight_id: flight.id, num_passengers: @search[:num_passengers] }, class: "inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto" %>
    <%# <button class="inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto">Book It!</button> %>
    <% end %>
  </td>
</tr>

app/views/flights/_search_form.html.erb
<%= form_with url: "/flights", method: "get", local: true do |f| %>
  <%= f.label :from_airport_id, "From" %>
  <%= f.select :from_airport_id, options_from_collection_for_select(Airport.all, :id, :code, selected: @search.try!(:[], :from_airport_id)), :include_blank => true %>
  <%= f.label :to_airport_id, "To" %>
  <%= f.select :to_airport_id, options_from_collection_for_select(Airport.all, :id, :code, selected: @search.try!(:[], :to_airport_id)), :include_blank => true %>
  <%= f.label :num_passengers, "# Passengers" %>
  <%= f.number_field :num_passengers, value: @search.try!(:[], :num_passengers), min: 1, max: 4 %>
  <%= f.label :date, "Date" %>
  <% # build a collection select named :date where the options are only dates that have flights and ordered by soonest, format the dates in mm/dd/yy format %>
  <%= f.select :date, Flight.all.map { |f| f.departure_time.strftime("%m/%d/%Y") }.uniq.sort, selected: @search.try!(:[], :date) %>
  <%= f.submit "Search", class: "inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto" %>
<% end %>

app/views/flights/index.html.erb
<!-- render a flight partial for each flight -->
<div class="px-4 sm:px-6 lg:px-8">
  <div class="mb-10">
    <h2 class="text-xl font-bold text-indigo-900 mb-4">Flight Search</h2>
    <!-- render search form -->
    <%= render "search_form" %>
  </div>
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h2 class="text-xl font-bold text-indigo-900">Available Flights</h2>
    </div>
  </div>
  <div class="-mx-4 mt-4 ring-1 ring-gray-300 sm:-mx-6 md:mx-0 md:rounded-lg">
    <table class="min-w-full divide-y divide-gray-300">
      <thead>
        <tr>
          <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Route</th>
          <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 lg:table-cell">Departing</th>
          <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 lg:table-cell">Arriving</th>
          <th scope="col" class="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 lg:table-cell">Flight Time</th>
          <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Departure Time</th>
          <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6">
            <span class="sr-only">Select</span>
          </th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200 bg-white">
        <% @flights.each do |flight| %>
          <%= render "flight", flight: flight %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>